### ISSUE TITLE
Markdown content is not a file

### ISSUE THREAD

**Issue by rashad612** [jaydson/marked-metadata#1]
Can we use this package to parse markdown content sent as string ? i.e. it's not stored in physical file.

Example:

``` javascript
var content = someMarkdownGetter();
var md = new MarkedMetaData(content);
md.defineTokens('<!--', '-->');
var meta = md.metadata();
```

Pull request below.

**Comment by brandonb927** [comment]
This seems like a reasonable pull request, I'm +1'ing for support :)

**Comment by jaydson** [comment]
Done in https://github.com/jaydson/marked-metadata/pull/2
